services:
  - type: web
    name: n8n
    runtime: docker
    repo: https://github.com/piccolojpg-18/bot-cupom-maria
    plan: free
    dockerfilePath: ./n8n-dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "123456"
      - key: PORT
        value: "5678"
      - key: N8N_PORT
        value: "5678"
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    healthCheckPath: /healthz